// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrzLoBAyL_7HWroJHqaQc473JczDqoNtM',
    appId: '1:803261664937:web:1cd25961ac33d70f17e3b8',
    messagingSenderId: '803261664937',
    projectId: 'bajfba',
    authDomain: 'bajfba.firebaseapp.com',
    storageBucket: 'bajfba.firebasestorage.app',
    measurementId: 'G-Q19EJKQCEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIBxMYVMpqpk3ehV7EoYudIAMm3jmAm_8',
    appId: '1:803261664937:android:14d483ed9f6a563017e3b8',
    messagingSenderId: '803261664937',
    projectId: 'bajfba',
    storageBucket: 'bajfba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwFz-y4vZrrgyQFLtf5KUXs7FpuvFTrhw',
    appId: '1:803261664937:ios:2898c1bd6d62d86c17e3b8',
    messagingSenderId: '803261664937',
    projectId: 'bajfba',
    storageBucket: 'bajfba.firebasestorage.app',
    iosBundleId: 'com.example.multiportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwFz-y4vZrrgyQFLtf5KUXs7FpuvFTrhw',
    appId: '1:803261664937:ios:2898c1bd6d62d86c17e3b8',
    messagingSenderId: '803261664937',
    projectId: 'bajfba',
    storageBucket: 'bajfba.firebasestorage.app',
    iosBundleId: 'com.example.multiportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrzLoBAyL_7HWroJHqaQc473JczDqoNtM',
    appId: '1:803261664937:web:dc56301b96cbcc9517e3b8',
    messagingSenderId: '803261664937',
    projectId: 'bajfba',
    authDomain: 'bajfba.firebaseapp.com',
    storageBucket: 'bajfba.firebasestorage.app',
    measurementId: 'G-144RPS6E2G',
  );
}
